// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'eu-west-1:df158b25-b10e-4278-aff1-2d50c134c094',
    'aws_cognito_region': 'eu-west-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'portfoliosite-hosting-mobilehub-2100613779',
    'aws_content_delivery_bucket_region': 'eu-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3etb9mzseq3b0.cloudfront.net',
    'aws_mobile_analytics_app_id': 'a15aababeab74bbb9a86a92605bf9569',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '77c2b6f8-b35b-4fa7-97d8-c890291762e0',
    'aws_project_name': 'portfolio-site',
    'aws_project_region': 'eu-west-1',
    'aws_resource_name_prefix': 'portfoliosite-mobilehub-2100613779',
}

export default awsmobile;
